Vagrant.configure('2') do |config|
  config.vm.box = "peru/ubuntu-18.10-desktop-amd64"
  config.vm.box_version = "20181101.01"
  config.vm.hostname = 'ibm-cloud-workshop'
  config.vm.network "forwarded_port", guest: 3000, host: 12345

  config.vm.provision 'shell', privileged: true, inline: <<~SCRIPT
    apt-get upgrade
    snap install atom --classic

    # Enable install of cf, see https://docs.cloudfoundry.org/cf-cli/install-go-cli.html#pkg-linux
    wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
    echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list

    # Enable install of nodejs, see https://nodesource.com/blog/installing-node-js-tutorial-ubuntu/
    curl -sL https://deb.nodesource.com/setup_6.x | bash -

    apt-get update
    apt-get install -y git cf-cli nodejs npm build-essential
  SCRIPT

  config.vm.provision 'shell', privileged: false, inline: <<~SCRIPT
    touch ~/.hushlogin
  SCRIPT
end
